### ISSUE TITLE
[Publish our events] Publish new events in Slack

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#103]
Zapier is used to publish new meetups in Slack. Currently, it publish the meetup in the meetings channel.  There is an effort done to consolidate all channels to one - #general. 
The configuration is done manually.  Automation is in place.

**Comment by lioramilbaum** [comment]
The flow is: As soon as @Balex3000 creates a new meetup in Meetup, it should be published in the #general Slack chanel.
Currently, Zapier is doing the same, but publish it in the #meetings chanel. 
We want to drop Zapier and use our own service which does what it is doing right now and more in the future.

**Comment by ekirmayer** [comment]
@lioramilbaum - Should this be a real service or as part of the devopsloft site?

**Comment by ekirmayer** [comment]
@lioramilbaum - Glad to see that we are on the same page.

**Comment by lioramilbaum** [comment]
Using the slacker python module to publish messages in Slack. The preview section is still not published.

https://github.com/os/slacker/issues/150

**Comment by lioramilbaum** [comment]
consolidating the discussion to one issue #102
