### ISSUE TITLE
Easy slack join in from website and readme

### ISSUE THREAD

**Issue by ekirmayer** [devopsloft/devopsloft#120]
The slack channel should be accessible for registration request easily from the readme file and from the website.
I suggest to add it from the about page as well a nice link from the readme file

**Comment by lioramilbaum** [comment]
@ekirmayer Please label the issue if it is an Epic/Story/Task.

**Comment by ekirmayer** [comment]
@lioramilbaum  - I cant label issues. I dont have permissions to do this.

**Comment by lioramilbaum** [comment]
obsolete
