### ISSUE TITLE
[ Deployment ] Implement bootstrap-infra.sh tasks into Ansible

### ISSUE THREAD

**Issue by ynixon** [devopsloft/devopsloft#144]
#97 replace bootstrap-infra from bash to ansible playbook

**Comment by lioramilbaum** [comment]
@ynixon please refactor the code to provision with ansible_local. The reasoning is to avoid using ansible on the host machine. If the host machine is Windows than we have a blocker. Ansible is not running on Windows.
With ansible_local I can verify the ansible is running on the target machine (which is ubuntu)

**Comment by ynixon** [comment]
done on #160
