### ISSUE TITLE
fix port of ci/cd

### ISSUE THREAD

**Issue by yishaiz** [devopsloft/devopsloft#147]
The CI/CD sample contains using of port 80, which cause error of "permission denied".
This is due to using devopsloft user, which is not root.
Need to fix to port 5000

**Comment by noamgu** [comment]
@yishaiz this is the problem?
[cicd.sh](https://github.com/devopsloft/devopsloft/blob/master/workshops/cicd-with-vagrant/05/cicd.sh)

![image](https://user-images.githubusercontent.com/39539338/57189106-fd395c00-6f12-11e9-8f40-6cd56a472745.png)

**Comment by yishaiz** [comment]
hi
this is not relevant anymore.
issue already been handled.
thanks
