### ISSUE TITLE
reload provision is not working

### ISSUE THREAD

**Issue by yishaiz** [devopsloft/devopsloft#152]
In case of refresh the provision (vagrant reload --provision), there is a step of a question and after answer "y" it is stuck.

attached a screenshot.
![reload provision](https://user-images.githubusercontent.com/4790164/51302939-89934200-1a3c-11e9-8106-7128b3c15d41.png)

**Comment by Balex3000** [comment]
@yishaiz @ynixon @lioramilbaum 
Is this issue still relevant/was solved?

**Comment by lioramilbaum** [comment]
no

**Comment by ynixon** [comment]
I solved it with one of my PRs, forcing to use dev/stage/prod when using reload.
