### ISSUE TITLE
Define the methodology to handle multiple PRs for a single issue

### ISSUE THREAD

**Issue by lioramilbaum** [DevOpsLoft/DevOpsLoft#16]
Resolve the conflict between 2 PRs owned by 2 contributors which intends to resolve a single issue owned by one of the contributors.

We should define a culture which works for us and is used in the industry.

For example: 
issue #13 
[PR-12](https://github.com/DevOpsLoft/DevOpsLoft/pull/12)
[PR-13](https://github.com/DevOpsLoft/DevOpsLoft/pull/13)

**Comment by bregman-arie** [comment]
The methodology will as simple as "whoever assigned to the task, will perform it".
There will be no more than one assignee at any given point of time.

**Comment by lioramilbaum** [comment]
Sounds reasonable.
