### ISSUE TITLE
Provisioning failure in site.yml last step

### ISSUE THREAD

**Issue by Balex3000** [devopsloft/devopsloft#171]
![image](https://user-images.githubusercontent.com/23415765/54029482-370b1200-41b1-11e9-9c7d-dc3e1fc8f353.png)

It seems as the problem in file permission configuration in yml

![image](https://user-images.githubusercontent.com/23415765/54029628-bc8ec200-41b1-11e9-964f-6bb30f01c4ab.png)

I tried to change the permission to 0755 but still receiving the same error message

**Comment by lioramilbaum** [comment]
change the shebang back to '#!/usr/bin/env bash' and check if it helps.

**Comment by ynixon** [comment]
On PR #170, the same code is working for me fine.
checked from windows on dev and stage

**Comment by Balex3000** [comment]
> #!/usr/bin/env bash

this is what actually solved the problem. reverted back to original permission 0655 and still works

**Comment by lioramilbaum** [comment]
@ynixon do you have an idea why it worked
 differently?

**Comment by ynixon** [comment]
I don't think solution did the trick.
It is working for me without any change with no problem. And I have windows like Alex.
If the file exists with the right permissions, it should work. 
Maybe it is Vagrant issue. 
Try to check it again with no change, using the latest version of Vagrant.

**Comment by lioramilbaum** [comment]
which vagrant version are you using @Balex3000 ? @ynixon ?

**Comment by ynixon** [comment]
it worked fine on 2.2.3 and now I have just checked with 2.2.4 --> the same

**Comment by lioramilbaum** [comment]
well, now I think we know what was the reason. we can close this issue.
