### ISSUE TITLE
The virtualenv created by Travis is a python 2 environment

### ISSUE THREAD

**Issue by cjcj56** [devopsloft/devopsloft#181]
Problem: The virtualenv created by Travis is a python 2 environment.
Cause:  when using the 'virtualenv' key, ansible will build the virtual environment, if it doesn't exist yet. In case ansible creates the virtual environment, the python version of the environment will be the same of the python version running ansible, unless specified otherwise with the 'virtualenv_python' tag.
This causes the requirements to be installed for python 2, and when the application tries to start, it fails with the following error:
**Traceback (most recent call last):
  File "application.py", line 3, in <module>
    from flask import Flask, flash, render_template, redirect, url_for, request
ImportError: No module named 'flask'**
From Travis logs: (add the '-v' option to the 'ansible-playbook' command in '.travis.yml' file to see these logs)
TASK [Install requirments into virtualenv] *************************************
[0;33mchanged: [127.0.0.1] => {"changed": true, "cmd": ["/home/travis/build/cjcj56/devopsloft/venv/bin/**pip2**", "install", "-r", "/home/travis/build/cjcj56/devopsloft/requirements.txt"], "name": null, "requirements": "/home/travis/build/cjcj56/devopsloft/requirements.txt", "state": "present", **"stderr": "DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.\n", "stderr_lines": ["DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7."]**,

**Comment by lioramilbaum** [comment]
nice catch. asked @ynixon to review the PR.
