### ISSUE TITLE
application password can be seen via ps -ef 

### ISSUE THREAD

**Issue by ynixon** [devopsloft/devopsloft#183]
```
vagrant@ubuntu-bionic:~$ ps -ef |grep application.py
root     15403     1  0 12:05 ?        00:00:00 python3 application.py 127.0.0.1 root 12345
root     15412 15403  0 12:05 ?        00:00:01 /vagrant/venv/bin/python3 application.py 127.0.0.1 root 12345
vagrant  15508 15487  0 12:08 pts/0    00:00:00 grep --color=auto application.py
```

**Comment by ynixon** [comment]
we should let the startup.sh application to read the password variables instead of passing the variables from ansible

**Comment by lioramilbaum** [comment]
agree

**Comment by ShimiTaNaka** [comment]
I think that if we move the compose, then there is the notation of `env_file`, and regardless, it's best to allow the application to get these parameters from the environment, I think it would be the first step to resolve it

**Comment by lioramilbaum** [comment]
@ynixon I agree with @ShimiTaNaka. Would you like to revise your PR?

**Comment by ynixon** [comment]
already done
