### ISSUE TITLE
Bumpt python-slackclient package to 2.x

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#220]
A major python-slackclient  release  - 2.x. Upgrading required code changes.

**Comment by noamgu** [comment]
Duplicate of  #284.

Get you provide additional details regard the required changes?

**Comment by lioramilbaum** [comment]
I don't remember what changes are required. Tried to upgrade with no change with no avail.

**Comment by lioramilbaum** [comment]
@noamgu I have looked again at the code. We are using Slacker library. The one mentioned in this issue is no longer relevant. Closing.
