### ISSUE TITLE
Implement Travis

### ISSUE THREAD

**Issue by lioramilbaum** [DevOpsLoft/DevOpsLoft#24]
The MVP is checking that the website: www.devopsloft.io returns 200

**Comment by bregman-arie** [comment]
@lioramilbaum please add me as a collaborator in settings -> collaborators
or enable Travis here: https://travis-ci.org

**Comment by lioramilbaum** [comment]
Done that already. Let me know if you are about to work on this issue soon. We have a hackday today so I might have the time to hack it as well.

**Comment by bregman-arie** [comment]
@lioramilbaum I still get "Access request pending"
It should have sent you an email with me requesting permissions
