### ISSUE TITLE
Spin prod environment from multiple hosts

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#244]
The prod environment is spinned with Vagrant from one host. Now, I am working on another host. I have access to the project source files and everything required to deploy a new prod environment. But, I can’t tear down the current prod environment. All the vagrant data regarding the prod environment is stored locally on the first host. How do we address it?

**Comment by ynixon** [comment]
didn't check it, bout found: [How to export a Vagrant virtual machine to transfer it](https://stackoverflow.com/questions/20679054/how-to-export-a-vagrant-virtual-machine-to-transfer-it
)

Create a box from your current virtual environment, using **vagrant package** command:

http://docs.vagrantup.com/v2/cli/package.html

Then copy the box to the other pc, add it using vagrant box add and run it using vagrant up as usual.

Keep in mind that files in your working directory (the one with the Vagrantfile) are shared when the virtual machine boots, so you need to copy it to the other pc as well.

**Comment by lioramilbaum** [comment]
@ynixon What is the purpose of creating a box for our production environment. We use a dummy box because we spin it in AWS.
