### ISSUE TITLE
Convert spin.sh to python

### ISSUE THREAD

**Issue by Dmitry-Atn** [devopsloft/devopsloft#263]
Convert spin.sh to python3 in order to support various OS

**Comment by lioramilbaum** [comment]
First task is to fork this repo and clone it to your computer. Please update here if you are in and done.

**Comment by noamhasingit** [comment]
Done -> git clone https://github.com/devopsloft/devopsloft.git

**Comment by lioramilbaum** [comment]
@noamhasingit Did you clone to upstream repo or your fork? You should clone your fork.

**Comment by noamhasingit** [comment]
ok, you are right - fixed it and cloned my fork: git clone
https://github.com/noamhasingit/devopsloft.git

**Comment by lioramilbaum** [comment]
If one already forked and cloned his repo before, he should update his clone with the following commands:
git checkout master
git pull upstream master
git push origin master

**Comment by noamhasingit** [comment]
yes I know, but I prefer to go to another way: delete, fork again and clone :)

**Comment by lioramilbaum** [comment]
Wouldn't you like to understand the strait forward way?

**Comment by noamhasingit** [comment]
i do know it when i used the upstream directly i used git head reset. but
your way is good as well i will use it next time.

**Comment by lioramilbaum** [comment]
I have updated master with the changes done on this task. Now you have the chance to do it my way :-)

**Comment by noamhasingit** [comment]
yep - you are right :) now I see your commit on my local clone

commit 98b15e358e2e1057921ef21b5b6e4cc5d35a4276 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: 04d0310 51238dd
Author: Liora Milbaum <liora@lmb.co.il>
Date:   Sun Jul 28 13:29:42 2019 +0300

    Merge pull request #285 from devopsloft/feature/spin-to-python

    Feature/spin to python

**Comment by noamhasingit** [comment]
What next ? :)

**Comment by lioramilbaum** [comment]
Create a local branch and execute the command:
./spin.py

Let's see what is working and what is not.

**Comment by noamhasingit** [comment]
I raised one pull request.
but still need to work on this exception: 
TypeError: box_update() missing 2 required positional arguments: 'name' and 'provider'

I need to learn spin.sh in order to understand what is missing when running /spin.py -a up -e dev

**Comment by lioramilbaum** [comment]
Where are all the others who wanted to pitch in?

**Comment by noamhasingit** [comment]
Python vagrant is a Not a mature tool and full of bugs...I will have to invest more time than planned.

**Comment by sbardugo** [comment]
Hi, the update_box function you added to spin.py is expecting to get 2 parameters that aren’t set right now (name and provider). 
Can you please advise on the purpose of that function and what the parameters should be?
Thanks :)

**Comment by lioramilbaum** [comment]
@sbardugo Updating the vagrant box insures we are spinning the environment with the latest box version.

**Comment by noamhasingit** [comment]
You have to call it as is: v.box_update("ubuntu/bionic64","virtualbox")

**Comment by lioramilbaum** [comment]
folks, who is working on what? what is the status?

**Comment by hilsenrat** [comment]
Shiran and I will work on spinning the stage environment using the spin.py
@Noam, can you please update so we won’t do double work?

**Comment by lioramilbaum** [comment]
@hilsenrat Didn't you mean to ping @noamhasingit ?

**Comment by noamhasingit** [comment]
HI @hilsenrat, you are welcome to work on it, basically, the first thing is to add 2 input variables to: box_update() call.
 If you want my help let me know and I will join.
Noam

**Comment by noamhasingit** [comment]
It is not easy to use it on MAC (Ubuntu will probably work) , there are few limitations...still trying ti figure it out.

**Comment by noamhasingit** [comment]
Documented bug: https://www.virtualbox.org/ticket/18366

**Comment by lioramilbaum** [comment]
@noamhasingit Can you explain the problem, or better yet, provide a screenshot/screen recording?

**Comment by lioramilbaum** [comment]
@hilsenrat How are you and Shiran are doing?

**Comment by noamhasingit** [comment]
Focusing on DEV use case.
trying to fix boxUpdate in spin,py

so iterating all machines and once find the first one run box update
if I don't find it than using box_add and run box_update, but I get this error:
**he machine with the name 'ubuntu/bionic64' was not found configured for
this Vagrant environment.**

code:
```

def updateBox(envArray):
   v = vagrant.Vagrant(quiet_stdout=False, quiet_stderr=False)
   v.env = envArray
   machines = v.box_list()
   print (“List of existing machines: “)
   print(machines)
   for i in machines:
       print (i)
       if i.name == “ubuntu/trusty64”:
          v.box_update(“ubuntu/bionic64",“virtualbox”)
          v.box_prune()
          return
   v.box_add(“ubuntu/trusty64",“https://app.vagrantup.com/ubuntu/boxes/trusty64“,”virtualbox”)
   v.box_update(“ubuntu/bionic64”,“virtualbox”)
   v.box_prune()
```

**Comment by lioramilbaum** [comment]
Which repo/branch your are using?
Are you facing an error?

**Comment by lioramilbaum** [comment]
@noamhasingit i have tried to execute the following command on my mac:
' ./spin.py -e dev -a up'

output:
(venv) ➜  devopsloft git:(spin-python) ./spin.py -e dev -a up
==> stage: Box 'dummy' not installed, can't check for updates.
==> prod: Box 'dummy' not installed, can't check for updates.
==> dev: Checking for updates to 'ubuntu/bionic64'
    dev: Latest installed version: 20190627.1.0
    dev: Version constraints:
    dev: Provider: virtualbox
==> dev: Updating 'ubuntu/bionic64' with provider 'virtualbox' from version
==> dev: '20190627.1.0' to '20190807.0.0'...
==> dev: Loading metadata for box 'https://vagrantcloud.com/ubuntu/bionic64'
==> dev: Adding box 'ubuntu/bionic64' (v20190807.0.0) for provider: virtualbox
    dev: Downloading: https://vagrantcloud.com/ubuntu/boxes/bionic64/versions/20190807.0.0/providers/virtualbox.box
    dev: Download redirected to host: cloud-images.ubuntu.com
==> dev: Successfully added box 'ubuntu/bionic64' (v20190807.0.0) for 'virtualbox'!
The following boxes will be kept...
fedora/29-cloud-base (virtualbox, 29.20181024.1)
ubuntu/bionic64      (virtualbox, 20190807.0.0)
ubuntu/trusty64      (virtualbox, 20190429.0.1)
ubuntu/xenial64      (virtualbox, 20190617.0.0)

Checking for older boxes...
Removing box 'ubuntu/bionic64' (v20190627.1.0) with provider 'virtualbox'...
Working on environment: dev
Bringing machine 'dev' up with 'virtualbox' provider...
==> dev: You assigned a static IP ending in ".1" to this machine.
==> dev: This is very often used by the router and can cause the
==> dev: network to not work properly. If the network doesn't work
==> dev: properly, try changing this IP.
==> dev: Importing base box 'ubuntu/bionic64'...
==> dev: Matching MAC address for NAT networking...
==> dev: You assigned a static IP ending in ".1" to this machine.
==> dev: This is very often used by the router and can cause the
==> dev: network to not work properly. If the network doesn't work
==> dev: properly, try changing this IP.
==> dev: Checking if box 'ubuntu/bionic64' version '20190807.0.0' is up to date...

**Comment by noamhasingit** [comment]
I'm looking to use v.box_update.
So I have the machine in my lists:

NoamHas-MacBook-Pro:devopsloft noamhasin$ vagrant box list
transmit-split-1         (virtualbox, 0)
transmit-split-407       (virtualbox, 0)
transmit-split-dilithium (virtualbox, 0)
ubuntu/bionic64          (virtualbox, 20190807.0.0)_

However when using this command:

v.box_update(name=vagrant_box,provider=vagrant_box_provider)

I get the following error:

he machine with the name 'ubuntu/bionic64' was not found configured for
this Vagrant environment.

This is the full trace log - see the last line marked in bold, any idea how it works for you but not for me?


Traceback (most recent call last):
  File "./spin.py", line 101, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./spin.py", line 94, in main
    updateBox(envVars)
  File "./spin.py", line 71, in updateBox
    v.box_update(name=vagrant_box,provider=vagrant_box_provider)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vagrant/__init__.py", line 799, in box_update
    self._call_vagrant_command(['box', 'update', name, provider])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
**subprocess.CalledProcessError: Command '['/usr/local/bin/vagrant', 'box', 'update', 'ubuntu/bionic64', 'virtualbox']' returned non-zero exit status 1.**

**Comment by lioramilbaum** [comment]
The command should be:
```vagrant box update --box ubuntu/bionic64  --provider virtualbox```

Did you install the python modules listed in requirements.txt?
They should be installed in your virtualenv.
One of the is a version of python-vagrant which I modified and updated the box_update function

**Comment by noamhasingit** [comment]
Vagrant command works perfectly.
I have the latest greatest of python-vagrant 
I have looked on python python-vagrant code and it looks straight forward command.

I added debug messages to my vagrant virtualbox part and I see it calling it anc executing the following but still, I get a message, i'm sure this is not something big...:

**### The machine with the name 'ubuntu/bionic64' was not found configured for
this Vagrant environment.**

	`dev.vm.provider :virtualbox do |virtualbox,override|
      puts "Inside virtualbox dev"
     dev.vm.box = "ubuntu/bionic64"
      dev.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/bionic64"
      dev.vm.name = "ubuntu/bionic64"
      virtualbox.memory = 1024
       virtualbox.cpus = 2
       puts "Inside virtualbox dev end"
		end

`

**Comment by lioramilbaum** [comment]
@noamhasingit Are you using python-vagrant from here?
https://github.com/devopsloft/python-vagrant.git

Pay attention this is fork of the "official" package

**Comment by noamhasingit** [comment]
I did the following:
pip3 install python-vagrant

Requirement already satisfied: python-vagrant in **/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (0.5.16)**
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by noamhasingit** [comment]
DO I need to use this one instead?

git+https://github.com/devopsloft/python-vagrant.git

**Comment by lioramilbaum** [comment]
@noamhasingit YES :-)

**Comment by noamhasingit** [comment]
ok, it is working now and all my work so far was for nothing :(

**Comment by lioramilbaum** [comment]
@noamhasingit I think you learned a lot in the process. It was worth it. You will see.

**Comment by lioramilbaum** [comment]
@noamhasingit  Worth adding information to the README

**Comment by lioramilbaum** [comment]
@Balex3000 Removed the first obstacle which cause spin.py to break on my mac box. Can you please test it on your windows box? 
https://github.com/lioramilbaum/devopsloft/tree/spin

**Comment by lioramilbaum** [comment]
obsolete in favor of the docker solution
