### ISSUE TITLE
Leverging AWS S3 for vault backend

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#267]

**Comment by ShimiTaNaka** [comment]
Why did you pick S3?

**Comment by lioramilbaum** [comment]
Because AWS hosting us next week and I needed to choose a topic which is relevant. Do you have other suggestions?

**Comment by ShimiTaNaka** [comment]
There are many, just was curious to know why S3.
The most common way AFAIK is consul, but I'm not 100% sure if it's really needed here.

**Comment by lioramilbaum** [comment]
Right. But, this is what it is.

**Comment by lioramilbaum** [comment]
Let say we spinned a stage environment, injected some secrets to vault which uses s3 as a persistent storage. What is needed to be done to hook up to the existing data when respining the stage environment? Initialising a new vault container cleanup the data stored in previous vault run.

**Comment by lioramilbaum** [comment]
@ShimiTaNaka ^^^

**Comment by lioramilbaum** [comment]
Asked the community - https://groups.google.com/forum/#!topic/vault-tool/Nh4BFtDq4Mk

**Comment by ShimiTaNaka** [comment]
If the storage backend is S3, then there is no reason that the data will not persist.
