### ISSUE TITLE
Community Members Management

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#27]
Community Users should be managed and tracked. 
We can not relay on Facebook group members or any other social media channel. 

parent of #42

**Comment by antweiss** [comment]
Looks like this is more or less what I meant in FB discussion of features. Bu this is an epic, so I'll define a related user story

**Comment by Balex3000** [comment]
Design document (in progress...)
https://docs.google.com/document/d/1mo8dxjhqByyYfSe5ux7OedVDdZs8HRZEZJHUGmKdXXs/edit?usp=sharing

**Comment by greycat001** [comment]
As we spoke, I have found a promising Flask application that deals with user registration:
[https://github.com/lingthio/Flask-User](https://github.com/lingthio/Flask-User)
IMHO, worth checking.
