### ISSUE TITLE
Current quarter agenda tab

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#295]
User Story:
As an app user, I would like to review the current quarter workshops agenda.

Technical Details:

- Additional tab named 'Agenda'
- Embed Google sheet in the tab - link to the agenda sheet will be provided by @Balex3000

**Comment by leonicus** [comment]
Is this still relevant? Can we get a link? @lioramilbaum @Balex3000

**Comment by lioramilbaum** [comment]
No longer relevant. Closing.
