### ISSUE TITLE
Make social media links more visible

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#296]
The social media links are not visible enough, because they are placed in the bottom of the home page. 

They should be placed on the top of the page

**Comment by AI-BlackB0x** [comment]
hello Liora how can assign this issue to my i am a new with all stuff

**Comment by lioramilbaum** [comment]
@AI-BlackB0x Due to the long time that have passed since your comment... Are you still willing to implement this issue?
