### ISSUE TITLE
Rename the 'Contact Us' tab to 'About Us' tab

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#297]

**Comment by Guru227** [comment]
Should the file name also be changed?

**Comment by lioramilbaum** [comment]
If you think it has a value than do change it

**Comment by Guru227** [comment]
I shall leave the filename unchanged as it might cause unprecedented side-effects. Thanks for the guidance.

**Comment by Mohammed-Numan** [comment]
Is this done?

**Comment by lioramilbaum** [comment]
@Mohammed-Numan Good question. Will take a look if a PR was submitted. If yes, it is better to link it here @Guru227

**Comment by lioramilbaum** [comment]
Found it. #306
