### ISSUE TITLE
README fix - "!!! Don't forget to destroy the environment when you done to avoid unnecessary charges"

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#299]
The "!!!" should be at the end of the sentence

**Comment by Guru227** [comment]
Can I work on this?

**Comment by lioramilbaum** [comment]
Yes please. go ahead.

**Comment by lioramilbaum** [comment]
@Guru227 Wait.   @Nitish-apex already submitted a PR.

**Comment by Guru227** [comment]
Whoops. Already submitted a PR. My bad.

**Comment by lioramilbaum** [comment]
I have merged the PR @Nitish-apex submitted. Closing this issue as done.
