### ISSUE TITLE
Add links to social media accounts

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#30]
Facebook page and group
Meetup Group
Youtube
LinkedIn

**Comment by Balex3000** [comment]
We already have links to our facebook, meetup and github in footer of each page in our application.
Only link to our YouTube channel is missing.
Here is the link: https://www.youtube.com/channel/UChv_8AbbznYS-xa256nXV6w
It only should be added to footer file and it will appear in all pages.
* We need to discuss what to do with Contact Us page.

**Comment by Balex3000** [comment]
took icons from:
https://fontawesome.com/icons/slack?style=brands
for some reason slack icon is still the old one. 
but it is better than nothing
