### ISSUE TITLE
Spin environment with Docker

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#307]
As a maintainer, I would like it to work on any of the following operating systems: Linux, OS-X and Windows.
As a maintainer, I would like to perform minimum manual steps before I execute this automation.

Acceptance Criteria,
Any of the environments: DEV/STAGE/PROD is spawned or teared by the automation

**Comment by sk3pp3r** [comment]
you can use `platform` module 

import platform 
plt = platform.system()

```
if plt == "Windows":
    print("Your system is Windows")
    # do x y z
elif plt == "Linux":
    print("Your system is Linux")
    # do x y z
elif plt == "Darwin":
    print("Your system is MacOS")
    # do x y z
else:
    print("Unidentified system")

```

**Comment by leonicus** [comment]
So, as far as requirements go, I think first thing is to read the variables from .env into container and pip install requirements.txt
We need to make a decision regarding where will vagrant go in this flow...As an idea, it might be best to go all the way and dockerize the app as well, leaving Vagrant alone, but that might be a lot of extra effort with little gains.

**Comment by markrity** [comment]
@sk3pp3r 
There is no need that , since docker is going to spin the process up. There is no need in understanding which platform it runs on.

**Comment by markrity** [comment]
@lioramilbaum 
Can you please provide more information on what you expect to "spin up" when running the automation process.
For each env.
Something like sequence diagram , but just in words. As a good story should be.

**Comment by lioramilbaum** [comment]
@markrity I can try, but I would guess @ShimiTaNaka has a clearer picture than I do.
BTW, is there still a need to run the spin.py command in the container or can we reuse the spin.sh for that matter?

**Comment by lioramilbaum** [comment]
@sk3pp3r Not sure I am following as to how this snipped can be of use. Please elaborate.

**Comment by lioramilbaum** [comment]
@leonicus See my previous comment about utilising python or bash in the container.

**Comment by leonicus** [comment]
That's related to how much of the process is containerized. I thought python was better to interact with to other entities in the host os, but if everything (e.g vagrant) will run from the container, we can use spin.sh

**Comment by lioramilbaum** [comment]
@leonicus I have no idea it spining the VM inside the container is what we can do. Let's wait @ShimiTaNaka's advice.

**Comment by markrity** [comment]
@lioramilbaum In docker we can use any script that we want , if spin.sh is good enough , it can be easily used.

**Comment by markrity** [comment]
The main reason I'm asking for a detailed user story , is to make it perfect on first try.
Also the whole project management , should be done the right way , so Stories should be written clearly.

**Comment by ShimiTaNaka** [comment]
@lioramilbaum Why would you want to spin the VM inside the container?

**Comment by leonicus** [comment]
@ShimiTaNaka, @markrity  It's an option. As far as I understand from a cursory glance at the script, it has to provide configuration options and files for vagrant deployment. If the vagrant process is running in the host OS, we still have to deal with platform agnostic commands for those options, even if they run from container (hence spin.py). A different approach would be to run the vagrant in the container or in a separate container of our choice, or to dockerize the app as well.

**Comment by ShimiTaNaka** [comment]
@leonicus Don't think it's an option, not sure it's even feasible let alone, recommended.
The question is, why would you want to do that, what is the gain?
On windows for example, you already need a VM to run docker, why do you need to pin up yet another VM only to run other docker containers in it?

**Comment by leonicus** [comment]
It's feasible from what I read, a bit troublesome. The gain is running independently from the platform. I might be missing something, but what is the alternative? spin.sh is good for configuring all the variables, etc within the container, but to interact with the host OS we still need a platform agnostic interface. So we could stick with spin.py and just dockerize it so we can take care of all the pip dependencies etc in the docker file. But I don't see how we can run just spin.sh from a container and it will work on windows host

**Comment by ShimiTaNaka** [comment]
We can't just run it.
Again, it may be possible to interact with Virtualbox from within the container, but why would linux users have to run VirtualBox to begin with?
The issue is that there is a goal to make sure "Everything will be automated and unified"
That's not possible, there are some aspects that has to happen manually by the user/developer, I think, that *those* should be defined first, and then we can move on.
Doing manual installation of VBox, then docker-machine, in order to run docker container, that spins up another VM, which inside runs other dockers.. is the reverse of simplicity.
Spin.sh/py can be converted to simply run the relevant commands and interact with the docker engine directly, it will not, however, solve issues of exposing ports and directories specifically on windows machines.

**Comment by leonicus** [comment]
@ShimiTaNaka I agree

**Comment by leonicus** [comment]
I agree about the first part. Lost you on the last assertion. The purpose of the spin script is to prepare the environment and the docker process was a suggestion to make that process unified across platforms. We are running a bit in circles, let's continue as @markrity suggested, with a step by step description of all the operations spin.sh/py has to perform and then we can decide on the benefits and cost of dockerizing it. Can you help with this, @ShimiTaNaka ?

**Comment by ShimiTaNaka** [comment]
With breaking is up? I can, but I think it would be wiser someone else will do it as I wan't part of writing it, so I assume others are familiar with it more than I am.

**Comment by leonicus** [comment]
OK. I have no idea who would be wiser, I'm kind of new here :) I think Liora suggested you could do it best

**Comment by lioramilbaum** [comment]
@ShimiTaNaka Can we start with MVP? Can you provide instructions on how to start?

**Comment by ShimiTaNaka** [comment]
@lioramilbaum for a start, you would need to install docker on the laptop
For windows, you can use either Linux subsystem for Windows, and install docker natively (https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) or docker-machine (https://docs.docker.com/docker-for-windows/install/)

The next phase would be to setup the mapping properly (if using docker-for-windows) since there *is* VirtualBox there.

Then you need to run the spin.py from a container, and fix it (there will be changes)
Once done, you should create a Dockerfile for the initial spin up (with all the spin.py dependencies)

and last, Documentation

**Comment by lioramilbaum** [comment]
@ShimiTaNaka Thanks and good morning :-) @markrity @leonicus Can you take it from here?

**Comment by leonicus** [comment]
I can take this initial step, since it seems it will also help us understand better the design we want. As long as @markrity is in agreement, since he started with this :)

**Comment by lioramilbaum** [comment]
@leonicus I believe you can start the implementation

**Comment by leonicus** [comment]
@lioramilbaum  OK, will do. I hope to have a working basis by EOW

**Comment by leonicus** [comment]
I created a basic docker file that solves the dependencies, etc... for spin.py (https://github.com/devopsloft/devopsloft/pull/309). Now there is the issue that spin.py is supposed to call vagrant executable with the relevant parameters- Before I invest more time in communicating with the exe (named pipe for example), I'd like to assess once more if we are on the same page- we want to run python-vagrant from the container, or some other solution to raise the app VM? @lioramilbaum @ShimiTaNaka @markrity

**Comment by ShimiTaNaka** [comment]
Don't think it would be wise to contact Vagrant from within the container, we should aim to work around it.
Essentially, Vagrant starts up the machine (docker-machine does it for you)
and then runs containers (that you can do from the spin.py container)

**Comment by leonicus** [comment]
@ShimiTaNaka Thanks, I agree if so. But I'm guessing this is something that was done manually? (getting the containers up)? Because I don't see anything that does it in spin.py
Anyhow, If I understand you correctly, we can skip the vagrant steps, and I'm guessing the other containers should be brought up from docker-composer.yml?

**Comment by ShimiTaNaka** [comment]
Exactly

**Comment by leonicus** [comment]
Thanks, so I'm closing the pull request...I'll create one with the necessary modifications by EOD/Tomorrow morning

**Comment by leonicus** [comment]
Done for now, please see https://github.com/devopsloft/devopsloft/pull/310.
Comments and improvements are welcome @lioramilbaum @ShimiTaNaka

**Comment by lioramilbaum** [comment]
I have merged your PR, although there is a huge technical debt we should address. Will open new issue/s for that.
