### ISSUE TITLE
Convert Travis deployment to use same pathway as dev env

### ISSUE THREAD

**Issue by leonicus** [devopsloft/devopsloft#318]
As a devopsloft contributor, I would like to have CI cover tests of the spinning up process, to make sure I am not breaking something in that flow
Currently, the scripts run by travis deploy the app directly from docker-compose, without using the spinning up process.

**Comment by lioramilbaum** [comment]
@leonicus Will you be working on this one?

**Comment by leonicus** [comment]
@lioramilbaum Yes, I can work on it, but will take some time since there are higher priorities (fixing staging deployment and documentation)

**Comment by lioramilbaum** [comment]
The CI is spinning the environment with the spin-docker.py script. This covers this issue.
