### ISSUE TITLE
the build of the spinner container fails 

### ISSUE THREAD

**Issue by Arielgordon123** [devopsloft/devopsloft#321]
Step 9/19 : COPY .env spin-docker.py docker-compose.yml createPemFiles.py in_docker.py /home/
COPY failed: stat /var/lib/docker/tmp/docker-builder365171566/in_docker.py: no such file or directory

**Comment by leonicus** [comment]
https://github.com/devopsloft/devopsloft/pull/324 Resolves this

**Comment by Arielgordon123** [comment]
#322 Resolves this

**Comment by lioramilbaum** [comment]
GitHub knows how to close an issue which is fixed by a PR when merged, if you specify in the first comment of the PR - 'Fixes #322'
