### ISSUE TITLE
Stage Environment - spin up

### ISSUE THREAD

**Issue by leonicus** [devopsloft/devopsloft#331]
Spinner process in docker should be able to raise a stage environment in AWS

**Comment by leonicus** [comment]
Worling on it

**Comment by Arielgordon123** [comment]
https://github.com/devopsloft/devopsloft/blob/811f96af17bbcae889139fd9465e44a2dd42f7f8/vault/config.hcl.j2#L12-L16
what is the way to get the AWS_S3_BUCKET variable without hard coding it

**Comment by lioramilbaum** [comment]
The value comes from an env file.  We can use vault or any other key-value store. @ShimiTaNaka thoughts?

**Comment by Arielgordon123** [comment]
> The value comes from an env file. 

i get that, but how could i get the value?
https://github.com/devopsloft/devopsloft/blob/811f96af17bbcae889139fd9465e44a2dd42f7f8/.env#L18

or i am missing something?

**Comment by lioramilbaum** [comment]
You should load the env file with python-dotenv

**Comment by Arielgordon123** [comment]
Sure. 
but the value is not in the file

**Comment by lioramilbaum** [comment]
Set it in .env.local

**Comment by Arielgordon123** [comment]
I knew I was missing something

**Comment by leonicus** [comment]
@Arielgordon123 , how is this related to this issue?

**Comment by Arielgordon123** [comment]
@leonicus you right it is not straightly related to this issue, sorry.

**Comment by leonicus** [comment]
@Arielgordon123 NP, I just wanted to know if you were planning changes  that relate to this issue since I'm working on it :)

**Comment by Arielgordon123** [comment]
Hi @leonicus 
currently I've no planning related to this issue.

p.s
just curious to know with which technology do you plan to use to spin the environment
