### ISSUE TITLE
web site not secure 

### ISSUE THREAD

**Issue by sk3pp3r** [devopsloft/devopsloft#343]
The access to the web site http://www.devopsloft.io/ isn`t via secured port (443)

please consider access website via HTTPS with a valid certificate.

**Comment by lioramilbaum** [comment]
@sk3pp3r Good issue. There were several tries in the past to imlement it. Are you on it?

**Comment by Arielgordon123** [comment]
take a look at #315 #320

**Comment by sk3pp3r** [comment]
> @sk3pp3r Good issue. There were several tries in the past to imlement it. Are you on it?

Yes. let`s do it
