### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by markrity** [DevOpsLoft/DevOpsLoft#37]
> The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

The following issue occurred recently on the website. 
10/4/2018

**Comment by lioramilbaum** [comment]
Fixed

**Comment by markrity** [comment]
@lioramilbaum The website is unreachable for me, pinging to it gives a timeout.
