### ISSUE TITLE
Monitoring System

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/devopsloft#38]
Like nagios, zabbix

Pingdome is a SaaS offering which is not free

**Comment by ShimiTaNaka** [comment]
@lioramilbaum I suggest opening a discussion on the monitoring system here/FB since each monitoring system has it's benefits/drawbacks.
We might end up with more than 1 since there is no "silver bullet"

**Comment by lioramilbaum** [comment]
@ShimiTaNaka Sounds good to me. Do discuss it with @eleyal. Just, use two guidelines: choose a technology which has a large echo system (and therefore listed in the job requirements) and the second one is- start with something (MVP), improvements will follow.

**Comment by noamhasingit** [comment]
Monitoring end user expirience is important as well. I suggest to have:

1. system monitoring: Memory , CPU
2. log monitoring: exception based monitoring on our web server
3. end user monitoring: use ab agent to run 24/7 url monitoring or end user monitoring senarios like sellenuim

any other suggestion?

**Comment by ShimiTaNaka** [comment]
For Mem/CPU etc, I'd suggest investigating prometheus, it has easy discovery system which will reduce work, not sure how their alerts are but they have good integration with grafana.
For end user I suppose if we have CloudFront or ALB we can use the built-in CloudWatch for metrics

**Comment by bregman-arie** [comment]
Personally, I vote for Prometheus. Easy to install, short learning curve, growing community, good integration with different systems (e.g. Jenkins).

**Comment by lioramilbaum** [comment]
Did we consider the infrastructure required for each one of the solutions?

**Comment by ShimiTaNaka** [comment]
@lioramilbaum the infra for prometheus is just ec2 machine whereas zabbix requires also a database.
CloudFront/Datadog etc requires nothing as I recall

**Comment by lioramilbaum** [comment]
@ShimiTaNaka OK. If everyone agrees this is the right operation, who can take the part of spinning the infrastructure, installing and configuring it? 
I would prefer it done in a workshop, such that more people from the community could learn from it.

**Comment by ShimiTaNaka** [comment]
@lioramilbaum I don't mind doing it as part of Terraform/Graphite-prometheus-grafana workshop

**Comment by lioramilbaum** [comment]
This workshop is not planned yet. Is there something minimal we can do till than (MVP) or any other solution which will start giving us value, although, not the perfect solution?

**Comment by ShimiTaNaka** [comment]
of course, but that depends on the knowledge of whomever is in the workshop

**Comment by lioramilbaum** [comment]
Right. We can emphasis that it is a master's workshop. Newbiz can join but the pase might be too quick for them. Let's move this conversation to Slack.

**Comment by noamhasingit** [comment]
i suggest to use single url monitoring to provide availability numbers.
whats about https://github.com/sanathp/statusok/blob/master/README.md

**Comment by lioramilbaum** [comment]
So, we have few solutions. Who can lead the solution by checking all the options and deciding on our MVP solution?

**Comment by lioramilbaum** [comment]
See my comment in #107

**Comment by lioramilbaum** [comment]
obsolete
