### ISSUE TITLE
[Members Management] Subscription

### ISSUE THREAD

**Issue by antweiss** [devopsloft/devopsloft#42]
This story is part of the User Management epic:  #27 
User story:
As an admin for DevOpsLoft I want to be able to add a User to the application.
A User is an entity whihc should have the following initial set of properties:

- username

- password

- email

parent of #73, parent of #79, parent of #80, parent of #81, parent of #82, parent of #91

**Comment by cubann** [comment]
@lioramilbaum Can you assign to me this issue please?

**Comment by lioramilbaum** [comment]
@cubann Feel free to work on it. Open a PR connected to this issue as a place holder. No one will touch it as long as a PR exists.

**Comment by lioramilbaum** [comment]
A person who wants to become a member should be able to subscribe.  
Subscription process will take his first name, last name and email and store it in a database.

**Comment by cubann** [comment]
@lioramilbaum open PR like this?

**Comment by cubann** [comment]
and btw why the name of the issue is Subscription? thought it should be admin functionality for admin panel according to the description,no?

**Comment by A-Jud** [comment]
@Balex3000  the following was discussed in 7/11 meeting we rename story - we changed the subscription story to Sign-up

**Comment by Balex3000** [comment]
Design document (in progress...)
https://docs.google.com/document/d/1mo8dxjhqByyYfSe5ux7OedVDdZs8HRZEZJHUGmKdXXs/edit?usp=sharing
