### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by lioramilbaum** [DevOpsLoft/DevOpsLoft#46]
use two social media groups to manage the community: 
[Facebook group](https://www.facebook.com/groups/devopsloft/)
[MeetUp group](https://www.meetup.com/DevOps-Loft/)

The communication options in both groups are limited. Facebook changed the exposure policies. It limits the exposure of FB group posts to its members timelines. (the group is not using financed campaign to boost posts exposure)
Meetup is intended for managing meet ups only. 

Therefore, keeping a mailing list of the community members will allow us to share important communications.

A subscription form can be used to gather subscribers. 
The data can be stored in a CSV file.

The information we want to gather is:
Name
Family Name
email
Newbie or Master

**Comment by lioramilbaum** [comment]
@jkubkub, @noamhasingit  Can you add some information here on how this epic was implemented.

**Comment by jkubkub** [comment]
@lioramilbaum 
- wtforms module to build form itself and validate data
- csv module to append data to file 
- flash module for showing alert message after subscription
Btw I really know that the code could be improved in perspective and modularity, should/can open an issue lets say "Refactoring application structure" ?

**Comment by lioramilbaum** [comment]
@jkubkub go ahead. Refactoring is important. It is part of the continues improvement culture.
