### ISSUE TITLE
Adding new user registeration client side form

### ISSUE THREAD

**Issue by noamhasingit** [DevOpsLoft/DevOpsLoft#49]
#46 Adding new user registeration client side form :http://127.0.0.1:5000/register

**Comment by jkubkub** [comment]
@lioramilbaum is this the same as #42 , isn’t it?

**Comment by lioramilbaum** [comment]
@jkubkub I am not sure. @noamhasingit, is this issue in work? or already implemented?

**Comment by noamhasingit** [comment]
This was implemented, but since @jkubkub  has done a duplication of it, I suggets to close the issue , I will clean my content.

**Comment by jkubkub** [comment]
@noamhasingit i thought that the registration and subscription to mailing , it is two different things

**Comment by noamhasingit** [comment]
no, I think we had missunderstanding.  I did the UI side only for the subscription  (I called it register)
BTW the subscription is still not working , should we open an issue?

**Comment by jkubkub** [comment]
@noamhasingit I thought that not all logged in user after registration could want to subscribe, so I think it is different functionality

**Comment by noamhasingit** [comment]
How can i login?

**Comment by noamhasingit** [comment]
ok, got it. i verified it and it works.

**Comment by lioramilbaum** [comment]
Our current use case is to create a mailing list and share important information with the community via email.
