### ISSUE TITLE
Substriction - support mobile phone 

### ISSUE THREAD

**Issue by noamhasingit** [devopsloft/devopsloft#57]
Using my android phone I see a small Substriction form. The form should be expanded to phone width and high.

**Comment by bregman-arie** [comment]
You mean Subscription?

**Comment by noamhasingit** [comment]
yes.

**Comment by bregman-arie** [comment]
so can you please fix the commit message?

**Comment by noamhasingit** [comment]
i did not deploy anything related to this item. this issue was opened as
placeholder for then future.

**Comment by cubann** [comment]
@bregman-arie I think you can close this issue, because it is already solved by previous PRs.
