### ISSUE TITLE
Create a bash script which provisions aws instance

### ISSUE THREAD

**Issue by lioramilbaum** [DevOpsLoft/DevOpsLoft#6]

**Comment by royhershko** [comment]
## i find this : 
aws ec2 run-instances --image-id ami-**xxxxxxxx** --count 1 --instance-type t1.micro --key-name **MyKeyPair** --security-groups my-sg 

the guide:  https://docs.aws.amazon.com/cli/latest/userguide/cli-ec2-launch.html

**Comment by lioramilbaum** [comment]
Unneeded for now
