### ISSUE TITLE
Provision ec2 instance in a VPC

### ISSUE THREAD

**Issue by lioramilbaum** [DevOpsLoft/DevOpsLoft#8]
Via AWS Console

**Comment by royhershko** [comment]
https://www.youtube.com/watch?v=fpxDGU2KdkA
Im follow this link

**Comment by royhershko** [comment]
https://www.youtube.com/watch?v=bGDMeD6kOz0 

this video great for the Basic VPC

**Comment by royhershko** [comment]
## What I learned from this Tutorial:
https://www.youtube.com/watch?v=bGDMeD6kOz0
-( 00:09 ) AWS VPC Introduction
-( 02:24 ) Amazon VPC Terminology
-( 02:45 ) Amazon VPC Definition
-( 03:06 ) Amazon VPC Diagram
-( 04:06 ) Default AWS VPC
-( 05:10 ) AWS Custom VPC
-( 05:32 ) Hardware VPN Access
-( 06:20 ) AWS VPC Peering
-( 07:36 ) AWS VPC Creation Demo
-( 13:10 ) AWS Elastic IP Address Demo
-( 15:54 ) AWS Subnet Tutorial
-( 19:55 ) AWS Networking Tutorial
-( 21:51 ) AWS Internet Gateway Creation
-( 23:26 ) AWS Route Table Tutorial
-( 33:27 ) Using Security Grops and Network ACLs in Amazon VPC
-( 33:44 ) AWS Security Gropus Tutorial
-( 48:00 ) AWS VPC Best Practices

**Comment by royhershko** [comment]
How do I know that : Provision EC2 in a VPC has passed successfully? @lioramilbaum

**Comment by lioramilbaum** [comment]
Go to AWS Console -> choose the ec2 instance provisioned -> See in the attributes bellow, the VPC ID has a value.

**Comment by royhershko** [comment]
OK ,  DONE.

**Comment by lioramilbaum** [comment]
Unneeded for now
