### ISSUE TITLE
[Persistence of the application] Database

### ISSUE THREAD

**Issue by Balex3000** [devopsloft/devopsloft#85]
* For dev and stage environment
** Backup to host before destroying
** When spinning an environment, check if there is a backup. If yes, restore it to the guest env

* For prod, ?

**Comment by noamgu** [comment]
# Data persistence
**The problem**: once the Vagrant environment has been replaced (upgrade, delete etc) all the data goes away.

Requirements:
1. On-prem & Cloud (AWS) support
2. Optional - Offline support

**Comment by ShimiTaNaka** [comment]
The issue will arise with any tool, even Terraform, if you run destroy, you lose the data.
My suggestion is to setup a periodic snapshot of the EC2 machine, as a temporary solution unless we want to go to something bit more complex which will fall out of the scope of vagrant

**Comment by ynixon** [comment]
Idea:
We will have a central replicated database on EC2 on a different machine.
On each creation of a new dev/stage/prod - we will pull all records from that database.
ONLY prod will have the automatic definition of replication back to that centralized DB.

Any database structure changes will be handled manually.

**Comment by noamgu** [comment]
We additional layers of complexity:
* VM that can go down & up on a daily basis
* Free solution, at-least for dev ENV (if possible) 
* Separate between 'real' Data for the Prod VS dummy for the dev environment

**Comment by noamgu** [comment]
@ynixon  & @ShimiTaNaka - Let's move offline (slack)

**Comment by lioramilbaum** [comment]
@noamgu Do you think it is valuable for other lofters if the discussions is moved offline?
