### ISSUE TITLE
[Subscription] get member status by email 

### ISSUE THREAD

**Issue by yishaiz** [devopsloft/devopsloft#91]
update is_member_exist function to return:
- whether email is exists.
- member status

**Comment by yishaiz** [comment]
@Balex3000 please notify me when you update the table schema

**Comment by lioramilbaum** [comment]
@yishaiz I don't understand what is the goal of this issue. Please amend the description.

**Comment by yishaiz** [comment]
@lioramilbaum i have removed it.
