### ISSUE TITLE
[ CI ] spin vagrant as part of CI

### ISSUE THREAD

**Issue by Balex3000** [devopsloft/devopsloft#94]
spin vagrant with the application for father testing

**Comment by OmriBarZik** [comment]
I did some research and I can't find a way to setup Vagrant in a CI System.
Travis runs on Vagrant but they don't give you the option to run VirtualBox in their containers
CircleCi runs on docker but they too don't give you the option to run VirtualBox on their containers. **but** they do give you an option to **run docker in their containers**
I found a CI system that does let you run VirtualBox on their containers [(AppVeyor)][AppVeyor] but I failed to run Vagrant on there. [refrence][AppVeyorRefrence]

[AppVeyor]: https://www.appveyor.com/
[AppVeyorRefrence]:https://github.com/jonashackt/vagrant-ansible-on-appveyor

**Comment by lioramilbaum** [comment]
obsolete
